using Azure;
using Azure.Communication.Email;
using System.Diagnostics;
using Umbraco_Project.Interfaces;
using Umbraco_Project.Models;

namespace Umbraco_Project.Services;
public class EmailService(IConfiguration configuration, EmailClient emailClient) : IEmailService
{
    private readonly IConfiguration _configuration = configuration;
    private readonly EmailClient _emailClient = emailClient;


    public async Task<EmailServiceResult> SendEmailConfirmationAsync(string email)
    {
		try
		{
            if (email == null || string.IsNullOrWhiteSpace(email))
                return new EmailServiceResult { Succeeded = false, Error = "Recipient email address is required." };

            var subject = $"Request recieved";
            var plainTextContent = $@"
            Hello,

            Thank you for getting in touch with Onatrix!

            We have received your message through our website and our team will review it shortly.
            One of our consultants will contact you as soon as possible — usually within 1–2 business days.

            Thank you for reaching out to Onatrix.
            We look forward to talking with you soon.

            Best regards,
            The Onatrix Team
            ";

            //htmlContent generated by ChatGPT5
            var htmlContent = @$"<!doctype html>
            <html lang=""en""><head>
            <meta charset=""utf-8""><meta name=""viewport"" content=""width=device-width"">
            <title>Onatrix – Confirmation</title>
            <style>@media screen{{.font{{font-family:-apple-system, Segoe UI, Roboto, Arial, sans-serif !important;}}}}</style>
            </head>
            <body style=""margin:0;padding:0;background:#F7F7F7;"">
            <div style=""display:none;max-height:0;overflow:hidden;opacity:0;"">
            We have received your message and will get back to you as soon as possible.
            </div>
            <table role=""presentation"" width=""100%"" cellspacing=""0"" cellpadding=""0"" border=""0"" style=""background:#F7F7F7;margin:0;padding:24px 12px;"">
            <tr><td align=""center"">
            <table role=""presentation"" width=""600"" cellspacing=""0"" cellpadding=""0"" border=""0"" style=""width:100%;max-width:600px;background:#FFFFFF;border-radius:10px;overflow:hidden;"">
            <tr><td style=""background:#4F5955;height:6px;line-height:6px;font-size:0;"">&nbsp;</td></tr>
            <tr><td align=""left"" class=""font"" style=""padding:24px 28px 8px 28px;font-family:Arial,Helvetica,sans-serif;"">
            <div style=""color:#4F5955;font-size:20px;font-weight:700;letter-spacing:.3px;"">Onatrix</div>
            </td></tr>
            <tr><td style=""padding:0 28px;"">
            <table role=""presentation"" width=""100%"" cellspacing=""0"" cellpadding=""0"" border=""0"" style=""background:#F2EDDC;border-radius:8px;"">
            <tr><td class=""font"" style=""padding:14px 16px;color:#4F5955;font-family:Arial,Helvetica,sans-serif;font-size:14px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;"">
            Request received
            </td></tr></table></td></tr>
            <tr><td class=""font"" style=""padding:22px 28px 8px 28px;color:#535656;font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:1.6;"">
            <p style=""margin:0 0 14px 0;"">Hello,</p>
            <p style=""margin:0 0 14px 0;"">Thank you for getting in touch with <strong style=""color:#4F5955;"">Onatrix</strong>!</p>
            <p style=""margin:0 0 14px 0;"">We have received your message through our website and our team will review it shortly. One of our consultants will contact you as soon as possible — usually within 1–2 business days.</p>
            <p style=""margin:0 0 14px 0;"">Thank you for reaching out to Onatrix. We look forward to talking with you soon.</p>
            <p style=""margin:18px 0 0 0;"">Best regards,<br><span style=""color:#4F5955;font-weight:600;"">The Onatrix Team</span></p>
            </td></tr>
            <tr><td style=""padding:8px 28px 0 28px;""><hr style=""border:none;height:1px;background:#EAEAEA;margin:0;""></td></tr>
            <tr><td class=""font"" style=""padding:12px 28px 24px 28px;color:#999999;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:1.6;"">
            <p style=""margin:0 0 6px 0;"">Onatrix • Klarabergsviadukten 90, 111 52 Stockholm</p>
            <p style=""margin:0 0 6px 0;""><a href=""mailto:info@onatrix.com"" style=""color:#4F5955;text-decoration:none;"">info@onatrix.com</a> • <a href=""https://onatrix.com"" style=""color:#4F5955;text-decoration:none;"">onatrix.com</a></p>
            <p style=""margin:0;"">You’re receiving this message because you contacted us via our website.</p>
            </td></tr>
            </table>
            </td></tr></table>
            </body></html>";

            var emailMessage = new EmailMessage(
                senderAddress: _configuration["ACS:SenderAddress"],
                recipients: new EmailRecipients([new(email)]),
                content: new EmailContent(subject)
                {
                    PlainText = plainTextContent,
                    Html = htmlContent
                });

            var emailSendOperation = await _emailClient.SendAsync(WaitUntil.Completed, emailMessage);

            return new EmailServiceResult { Succeeded = true, Message = "Email sent successfully." };
        }
		catch (Exception ex)
		{
            Debug.WriteLine($"Error sending confirmation email: {ex.Message}");
            return new EmailServiceResult { Succeeded = false, Error = "Failed to send email confirmation" };
		}
    }
}
